version: '3.9'
services:
  app:
    container_name: application
    image: something:v1
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    restart: always
    ports:
      - "8989:8989"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app